name: fp-ncurses-tui

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
    paths-ignore: [ "README.md", "history.md", "release-notes.md" ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Examples
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        lazarus-versions: [ stable ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
        with-cache: false

    - name: Build the Examples (Ubuntu)
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      run: |
        lazbuild -B --bm=Release "examples/one-form/oneform.lpi"
        lazbuild -B --bm=Release "examples/two-forms/twoforms.lpi"
        lazbuild -B --bm=Release "examples/component-label/component-label.lpi"
        lazbuild -B --bm=Release "examples/component-button/component-button.lpi"

    - name: Upload binary (Ubuntu)
      if: ${{ (matrix.operating-system == 'ubuntu-latest')  &&  (matrix.lazarus-versions == 'stable') }}
      uses: actions/upload-artifact@v4
      with:
        name: linux
        path: |
          bin/oneform
          bin/twoforms
          bin/component-label
          bin/component-button

  package-release:
    if: contains(github.ref, '/tags/')

    name: Package and create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set env
      run: echo "tag=${{ github.ref_name }}" >> "$GITHUB_ENV"

    - name: Download the Release binary
      uses: actions/download-artifact@v4
      with:
        name: linux
        path: examples-linux

    - name: List files
      run: ls -alF examples-linux

    - name: Create release files
      run: |
        cd examples-linux
        chmod +x oneform
        chmod +x twoforms
        chmod +x component-label
        chmod +x component-button
        tar -zcvf examples-${{ env.tag }}-x86_64-linux.tar.gz oneform twoforms component-label component-button

    - name: Generate Release Notes
      id: git-cliff
      uses: orhun/git-cliff-action@v4
      with:
        config: cliff.toml
        args: --latest  --strip header

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        name: Examples ${{ env.tag }}
        body: ${{ steps.git-cliff.outputs.content }}
        files: |
          examples-linux/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
