name: fp-ncurses-tui

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
    paths-ignore: [ "README.md", "history.md", "release-notes.md" ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Examples
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest, macos-latest ]
        lazarus-versions: [ stable, 3.4 ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
        with-cache: false

    - name: Build the Examples
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      run: |
        lazbuild -B --bm=Release "examples/one-form/oneform.lpi"
        lazbuild -B --bm=Release "examples/two-forms/twoforms.lpi"
        lazbuild -B --bm=Release "examples/component-label/component-label.lpi"
        lazbuild -B --bm=Release "examples/component-button/component-button.lpi"

    - name: Upload binary (Ubuntu)
      if: ${{ (matrix.operating-system == 'ubuntu-latest')  &&  (matrix.lazarus-versions == 'stable') }}
      uses: actions/upload-artifact@v4
      with:
        name: examples
        path: |
          bin/oneform
          bin/twoforms

  package-release:
    if: contains(github.ref, '/tags/')

    name: Package and create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Download the Release binary
      uses: actions/download-artifact@v4

    - name: List files
      run: ls -alF examples

    - name: Create release files
      run: |
        cd examples
        chmod +x oneform
        chmod +x twoforms
        chmod +x component-label
        chmod +x component-button
        tar -zcvf examples-${{ steps.vars.outputs.tag }}-x86_64-linux.tar.gz oneform twoforms component-label component-button
    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        name: Examples ${{ steps.vars.outputs.tag }}
        body_path: CHANGELOG.md
        files: |
          examples/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
